# This code-samples file is used by the MeiliSearch documentation
# Every example written here will be automatically fetched by
# the documentation on build
# You can read more on https://github.com/meilisearch/documentation/tree/master/.vuepress/code-samples
---
get_one_index_1: |-
  client.index('movies')
list_all_indexes_1: |-
  client.indexes
create_an_index_1: |-
  client.create_index('movies', primaryKey: 'movie_id')
update_an_index_1: |-
  client.index('movies').update(primaryKey: 'movie_id')
delete_an_index_1: |-
  client.delete_index('movies')
get_one_document_1: |-
  index.document(25684)
get_documents_1: |-
  index.documents(limit: 2)
add_or_replace_documents_1: |-
  index.add_documents([
    {
      id: 287947,
      title: 'Shazam',
      poster: 'https://image.tmdb.org/t/p/w1280/xnopI5Xtky18MPhK40cZAGAOVeV.jpg',
      overview: 'A boy is given the ability to become an adult superhero in times of need with a single magic word.',
      release_date: '2019-03-23'
    }
  ])
add_or_update_documents_1: |-
  index.update_documents([
    {
      id: 287947,
      title: 'Shazam ⚡️',
      genres: 'comedy'
    }
  ])
delete_all_documents_1: |-
  index.delete_all_documents
delete_one_document_1: |-
  index.delete_document(25684)
delete_documents_1: |-
  index.delete_documents([23488, 153738, 437035, 363869])
search_1: |-
  index.search('american ninja')
get_update_1: |-
  index.get_update_status(1)
get_all_updates_1: |-
  index.get_all_update_status
get_keys_1: |-
  client.keys
get_settings_1: |-
  index.settings
update_settings_1: |-
  index.update_settings({
    rankingRules: [
      'typo',
      'words',
      'proximity',
      'attribute',
      'wordsPosition',
      'exactness',
      'desc(release_date)',
      'desc(rank)'
    ],
    distinctAttribute: 'movie_id',
    searchableAttributes: [
      'uid',
      'movie_id',
      'title',
      'description',
      'poster',
      'release_date',
      'rank'
    ],
    displayedAttributes: [
      'title',
      'description',
      'poster',
      'release_date',
      'rank'
    ],
    stopWords: [
      'the',
      'a',
      'an'
    ],
    synonyms: {
      wolverine: ['xmen', 'logan'],
      logan: ['wolverine']
    }
  })
reset_settings_1: |-
  index.reset_settings
get_synonyms_1: |-
  index.synonyms
update_synonyms_1: |-
  index.update_synonyms({
    wolverine: ['xmen', 'logan'],
    logan: ['wolverine', 'xmen'],
    wow: ['world of warcraft']
  })
reset_synonyms_1: |-
  index.reset_synonyms
get_stop_words_1: |-
  index.stop_words
update_stop_words_1: |-
  index.update_stop_words(['of', 'the', 'to'])
reset_stop_words_1: |-
  index.reset_stop_words
get_ranking_rules_1: |-
  index.ranking_rules
update_ranking_rules_1: |-
  index.update_ranking_rules([
    'typo',
    'words',
    'proximity',
    'attribute',
    'wordsPosition',
    'exactness',
    'asc(release_date)',
    'desc(rank)'
  ])
reset_ranking_rules_1: |-
  index.reset_ranking_rules
get_distinct_attribute_1: |-
  index.distinct_attribute
update_distinct_attribute_1: |-
  index.update_distinct_attribute('movie_id')
reset_distinct_attribute_1: |-
  index.reset_distinct_attribute
get_searchable_attributes_1: |-
  index.searchable_attributes
update_searchable_attributes_1: |-
  index.update_searchable_attributes([
    'title',
    'description',
    'uid'
  ])
reset_searchable_attributes_1: |-
  index.reset_searchable_attributes
get_attributes_for_faceting_1: |-
  index.attributes_for_faceting
update_attributes_for_faceting_1: |-
  index.update_attributes_for_faceting([
    'genres',
    'director'
  ])
reset_attributes_for_faceting_1: |-
  index.reset_attributes_for_faceting
get_displayed_attributes_1: |-
  index.get_displayed_attributes
update_displayed_attributes_1: |-
  index.update_displayed_attributes([
    'title',
    'description',
    'release_date',
    'rank',
    'poster'
  ])
reset_displayed_attributes_1: |-
  index.reset_displayed_attributes
get_index_stats_1: |-
  client.index('movies').stats
get_indexes_stats_1: |-
  client.stats
get_health_1: |-
  client.health
update_health_1: |-
  client.update_health(false)
get_version_1: |-
  client.version
distinct_attribute_guide_1: |-
  client.index('jackets').update_distinct_attribute('product_id')
field_properties_guide_searchable_1: |-
  index.update_searchable_attributes([
    'uid',
    'movie_id',
    'title',
    'description',
    'poster',
    'release_date',
    'rank'
  ])
field_properties_guide_displayed_1: |-
  index.update_settings({
    displayedAttributes: [
      'title',
      'description',
      'poster',
      'release_date',
      'rank'
    ]
  })
filtering_guide_1: |-
  index.search('Avengers', { filters: 'release_date > 795484800' })
filtering_guide_2: |-
  index.search('Batman', {
    filters: 'release_date > 795484800 AND (director = "Tim Burton" OR director = "Christopher Nolan")'
  })
filtering_guide_3: |-
  index.search('horror', { filters: 'director = "Jordan Peele"' })
filtering_guide_4: |-
  index.search('Planet of the Apes', {
    filters: 'rating >= 3 AND (NOT director = "Tim Burton")'
  })
search_parameter_guide_query_1: |-
  index.search('shifu')
search_parameter_guide_offset_1: |-
  index.search('shifu', {
    offset: 1
  })
search_parameter_guide_limit_1: |-
  index.search('shifu', {
    limit: 2
  })
search_parameter_guide_retrieve_1: |-
  index.search('shifu', {
    attributesToRetrieve: ['overview', 'title']
  })
search_parameter_guide_crop_1: |-
  index.search('shifu', {
    attributesToCrop: ['overview'],
    cropLength: 10
  })
search_parameter_guide_highlight_1: |-
  index.search('shifu', {
    attributesToHighlight: ['overview']
  })
search_parameter_guide_matches_1: |-
  index.search('n', {
    filters: 'title="Kung Fu Panda"',
    attributesToHighlight: ['overview'],
    matches: true
  })
search_parameter_guide_filter_1: |-
  index.search('n', {
    filters: 'title = Nightshift'
  })
search_parameter_guide_filter_2: |-
  index.search('n', {
    filters: 'title="Kung Fu Panda"'
  })
settings_guide_synonyms_1: |-
  index.update_settings({
    synonyms: {
      sweater: ['jumper'],
      jumper: ['sweater']
    }
  })
settings_guide_stop_words_1: |-
  index.update_settings({
    stopWords: [
      'the',
      'a',
      'an'
    ]
  })
settings_guide_ranking_rules_1: |-
  index.update_settings({
    rankingRules: [
      'typo',
      'words',
      'proximity',
      'attribute',
      'wordsPosition',
      'exactness',
      'asc(release_date)',
      'desc(rank)'
    ]
  })
settings_guide_distinct_1: |-
  client.index('jackets').update_distinct_attribute('product_id')
settings_guide_searchable_1: |-
  index.update_settings({
    searchableAttributes: [
      'uid',
      'movie_id',
      'title',
      'description',
      'poster',
      'release_date',
      'rank'
    ]
  })
settings_guide_displayed_1: |-
  index.update_settings({
    displayedAttributes: [
      'title',
      'description',
      'poster',
      'release_date',
      'rank'
    ]
  })
add_movies_json_1: |-
  require 'json'

  movies_json = File.read('movies.json')
  movies = JSON.parse(movies_json)
  index.add_documents(movies)
documents_guide_add_movie_1: |-
  index.add_documents([{
    "movie_id": "123sq178",
    "title": "Amelie Poulain"
  }])
search_guide_1: |-
  index.search('shifu', {
    limit: 5,
    offset: 10
  })
search_guide_2: |-
  index.search('Avengers', {
    filters: 'release_date > 795484800'
  })
getting_started_create_index_md: |-
  ```bash
  $ bundle add meilisearch
  ```

  ```ruby
  require 'meilisearch'

  client = MeiliSearch::Client.new('http://127.0.0.1:7700')
  index = client.create_index('movies')
  ```

  [About this gem](https://www.github.com/meilisearch/meilisearch-ruby)
getting_started_add_documents_md: |-
  ```ruby
  require 'json'

  movies_json = File.read('movies.json')
  movies = JSON.parse(movies_json)
  index.add_documents(movies)
  ```

  [About this gem](https://www.github.com/meilisearch/meilisearch-ruby)
getting_started_search_md: |-
  ```ruby
  index.search('botman')
  ```

  [About this gem](https://www.github.com/meilisearch/meilisearch-ruby)
faceted_search_update_settings_1: |-
  index.update_attributes_for_faceting([
    'director',
    'genres'
  ])
faceted_search_facet_filters_1: |-
  index.search('thriller', {
    facetFilters: [['genres:Horror', 'genres:Mystery'], 'director:Jordan Peele']
  })
faceted_search_facets_distribution_1: |-
  index.search('Batman', {
    facetsDistribution: ['genres']
  })
faceted_search_walkthrough_attributes_for_faceting_1: |-
  index.update_attributes_for_faceting([
    'director',
    'producer',
    'genres',
    'production_companies'
  ])
faceted_search_walkthrough_facet_filters_1: |-
  index.search('thriller', {
    facetFilters: [['genres:Horror', 'genres:Mystery'], 'director:Jordan Peele']
  })
faceted_search_walkthrough_facets_distribution_1: |-
  index.search('Batman', {
    facetsDistribution: ['genres']
  })
